(function() {
    'use strict';
    const form=document.getElementById('flz-bq-full-access-form');const history=document.getElementById('flz-bq-full-access-history');const status=document.getElementById('flz-bq-full-access-status');if(!form||!history||!status)return;
    const request=async(path,options={})=>{const headers=options.headers||{};if(options.method&&options.method!=='GET')headers.requesttoken=OC.requestToken;const response=await fetch(OC.generateUrl('/apps/flzbqplanung'+path),{credentials:'same-origin',...options,headers});const payload=await response.json();if(!response.ok)throw new Error(payload.message||'Anfrage fehlgeschlagen.');return payload;};
    const date=value=>value?new Date(value).toLocaleString('de-DE'):'—';
    const load=async()=>{try{const state=await request('/api/admin/full-access');history.replaceChildren();if(!state.history?.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=6;cell.textContent='Noch keine Freigaben protokolliert.';row.append(cell);history.append(row);return;}state.history.forEach(grant=>{const row=document.createElement('tr');const active=!grant.revokedAt&&Date.parse(grant.startsAt)<=Date.now()&&Date.parse(grant.endsAt)>Date.now();[grant.targetUid,grant.grantedBy,date(grant.startsAt),date(grant.endsAt),grant.revokedAt?date(grant.revokedAt):(active?'Aktiv':'Planmäßig beendet')].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell);});const action=document.createElement('td');if(active){const button=document.createElement('button');button.type='button';button.textContent='Widerrufen';button.dataset.revokeUid=grant.targetUid;action.append(button);}row.append(action);history.append(row);});}catch(error){status.textContent=error.message||'Die Vollzugriffshistorie konnte nicht geladen werden.';}};
    form.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(form);if(data.get('enabled')!=='on')return;try{await request('/api/admin/full-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetUid:String(data.get('targetUid')||'').trim(),durationMinutes:Number(data.get('durationMinutes'))})});form.elements.enabled.checked=false;status.textContent='Der zeitlich begrenzte Vollzugriff wurde aktiviert.';await load();}catch(error){status.textContent=error.message||'Der Vollzugriff konnte nicht aktiviert werden.';}});
    history.addEventListener('click',async event=>{const button=event.target.closest('button[data-revoke-uid]');if(!button)return;button.disabled=true;try{await request('/api/admin/full-access/'+encodeURIComponent(button.dataset.revokeUid),{method:'DELETE'});status.textContent='Der Vollzugriff wurde widerrufen.';await load();}catch(error){button.disabled=false;status.textContent=error.message||'Der Vollzugriff konnte nicht widerrufen werden.';}});void load();
})();
